""" Starterkit flavors in form of Bazel execution platforms. """

package(default_visibility = ["//visibility:public"])

# Anything falling in this category should not execute
platform(name = "DEV_NULL_PLATFORM")

platform(
    name = "starterkit-x86_64-linux",
    constraint_values = [
        "@platforms//os:linux",
        "@platforms//cpu:x86_64",
    ],
    exec_properties = {
        "OSFamily": "Linux",
    },
)

# Please be aware,
# that you should select only ONE
# of the following platforms to be registered,
# or add more specific constraints.

platform(
    name = "ash",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash:b2x3hrx0jwb4d1zn8p5n5h4hgclmbaw4",
    },
)

platform(
    name = "ash-bash",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash:r4qfzcg8dzd7wzd5vjb5z77bblimpfcn",
    },
)

platform(
    name = "ash-bash-coreutils",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-coreutils:h2ldva1rfgfgz8pzx7zsrzc002rmwjsb",
    },
)

platform(
    name = "ash-bash-coreutils-i686",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-coreutils-i686:2gx0pa37kg56mpbfaa9m4l5aic0ichrn",
    },
)

platform(
    name = "ash-bash-coreutils-i686-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-coreutils-i686-cc:x80837np2m83ry4gyn46lm2w6idf8y3v",
    },
)

platform(
    name = "ash-bash-coreutils-i686-cc-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-coreutils-i686-cc-x86_64:8y9lf095dbwb5hqwg4z33s9vy484pyhb",
    },
)

platform(
    name = "ash-bash-coreutils-i686-cc-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-coreutils-i686-cc-x86_64-cc:hwgjfd7q25rqhy5w0f17m1ynrlh1k2ij",
    },
)

platform(
    name = "ash-bash-coreutils-i686-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-coreutils-i686-x86_64:vp0mwjppz2lq9yk2xgyf3p239ragpkw2",
    },
)

platform(
    name = "ash-bash-coreutils-i686-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-coreutils-i686-x86_64-cc:siqx41fbr9cyfafagz4qqn36877hdph0",
    },
)

platform(
    name = "ash-bash-coreutils-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-coreutils-x86_64:xhpfvgm7aqwskgb6cj73xwv87b3plwvq",
    },
)

platform(
    name = "ash-bash-coreutils-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-coreutils-x86_64-cc:sx82gwqpjjp69cnkbcq254fq16n6x1sf",
    },
)

platform(
    name = "ash-bash-i686",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-i686:cvfgh7yfhb0mdk9zm97si5vnaxd9zkm4",
    },
)

platform(
    name = "ash-bash-i686-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-i686-cc:73y1gxrm2ca7q938sw680ddfwdlrgxpm",
    },
)

platform(
    name = "ash-bash-i686-cc-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-i686-cc-x86_64:0k7bzbs8fxb3vnci88xd7fs6fvdjbcfy",
    },
)

platform(
    name = "ash-bash-i686-cc-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-i686-cc-x86_64-cc:f2ljwi9xgmqbjkljppvzp7wvc1v3xsb1",
    },
)

platform(
    name = "ash-bash-i686-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-i686-x86_64:5dwqjzjm4nrai3fz7r5lj1xxdj0fnrwf",
    },
)

platform(
    name = "ash-bash-i686-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-i686-x86_64-cc:6v3d743abfd73dmg0wh2cgbxn8v7nl23",
    },
)

platform(
    name = "ash-bash-strace",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-strace:j1mq76nkl0n6gwc9rqjfzz1a51hjjgc1",
    },
)

platform(
    name = "ash-bash-strace-coreutils",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-strace-coreutils:4g6ddvm7684vwf5yf05acd1y1m07d9l4",
    },
)

platform(
    name = "ash-bash-strace-coreutils-i686",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-strace-coreutils-i686:r2pgzxrgxmii4j0q0yjn46akgz5q9v3i",
    },
)

platform(
    name = "ash-bash-strace-coreutils-i686-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-strace-coreutils-i686-cc:9d6ivrcj8xx8qc4xikl0c6ld79wbkiwp",
    },
)

platform(
    name = "ash-bash-strace-coreutils-i686-cc-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-strace-coreutils-i686-cc-x86_64:0c3axn9x0bbcdc34qgdc9143pjz5fp3l",
    },
)

platform(
    name = "ash-bash-strace-coreutils-i686-cc-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-strace-coreutils-i686-cc-x86_64-cc:0f07xb799y3ywdlnh42vbp5qcv54hn96",
    },
)

platform(
    name = "ash-bash-strace-coreutils-i686-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-strace-coreutils-i686-x86_64:waz315f8k294brqxchwsavz784kdbh80",
    },
)

platform(
    name = "ash-bash-strace-coreutils-i686-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-strace-coreutils-i686-x86_64-cc:axdd4003i0yph6xks3h058hc3m2lg9nr",
    },
)

platform(
    name = "ash-bash-strace-coreutils-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-strace-coreutils-x86_64:dsi70ijjjxfmmhssl8k2941fwlq5xnx9",
    },
)

platform(
    name = "ash-bash-strace-coreutils-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-strace-coreutils-x86_64-cc:cdk62gvapym61cxf43isxbhmd27qad9x",
    },
)

platform(
    name = "ash-bash-strace-i686",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-strace-i686:fp9fr5l61gk8ljcbz0r61lpzw6whj310",
    },
)

platform(
    name = "ash-bash-strace-i686-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-strace-i686-cc:dvxa5j88655zgzj87lvl8dkx3zam71ns",
    },
)

platform(
    name = "ash-bash-strace-i686-cc-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-strace-i686-cc-x86_64:kwa3m08ym5dd4pyklvnb36mrv9443m9m",
    },
)

platform(
    name = "ash-bash-strace-i686-cc-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-strace-i686-cc-x86_64-cc:0g68fjl63fx5lq2rknlgc19hxhzyxgj0",
    },
)

platform(
    name = "ash-bash-strace-i686-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-strace-i686-x86_64:0n038rjxhl4avcdp7wz499fqr7r5dkbl",
    },
)

platform(
    name = "ash-bash-strace-i686-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-strace-i686-x86_64-cc:ildiv94z2a0lhvjm799wkrn5xsab3s41",
    },
)

platform(
    name = "ash-bash-strace-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-strace-x86_64:y97vz1k7v58pj6qmy9ajhz52kv5k16dv",
    },
)

platform(
    name = "ash-bash-strace-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-strace-x86_64-cc:7b29iqbqhfrbbrdz5hgyp1iaghw9q350",
    },
)

platform(
    name = "ash-bash-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-x86_64:vb2an2akn30bq07f3vgg2gwml8m8faz0",
    },
)

platform(
    name = "ash-bash-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-x86_64-cc:27b1x96idy57xzhpanx2afj12lllhx4w",
    },
)

platform(
    name = "ash-coreutils",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-coreutils:ip3ng77hpg182l0z6b8akqac7qjj7wy4",
    },
)

platform(
    name = "ash-coreutils-i686",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-coreutils-i686:xn4w5wmbzcbvqzhd5cp9zpmabmz1yjfz",
    },
)

platform(
    name = "ash-coreutils-i686-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-coreutils-i686-cc:ggiwa6vvdqav6dwyz4vqdqp6scgb1k48",
    },
)

platform(
    name = "ash-coreutils-i686-cc-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-coreutils-i686-cc-x86_64:0frkvlk5c6rcph5k44pz55r9fvpyd0mb",
    },
)

platform(
    name = "ash-coreutils-i686-cc-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-coreutils-i686-cc-x86_64-cc:5a7nxsywmhpbrk6d1sbkdg8mr7963y1f",
    },
)

platform(
    name = "ash-coreutils-i686-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-coreutils-i686-x86_64:40n54dpks4q1gcikyykyhz2rn276ba6l",
    },
)

platform(
    name = "ash-coreutils-i686-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-coreutils-i686-x86_64-cc:jsyssl4h8yn9j0llw3qsm5mvcg5fgj86",
    },
)

platform(
    name = "ash-coreutils-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-coreutils-x86_64:6gxb66aa4ra01bc3j3pa2n4rm59s7dwy",
    },
)

platform(
    name = "ash-coreutils-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-coreutils-x86_64-cc:q3vcicl4ns0dsihvy2a0d9navzx48kkm",
    },
)

platform(
    name = "ash-i686",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-i686:z0w1wc79j46wb09d5wayvi2vah23walw",
    },
)

platform(
    name = "ash-i686-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-i686-cc:d1l4lavh77k00ssv1drpswg6jc7nqnjj",
    },
)

platform(
    name = "ash-i686-cc-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-i686-cc-x86_64:bby7b5vkq3r6d1ifaclcfyl4fhl60bmx",
    },
)

platform(
    name = "ash-i686-cc-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-i686-cc-x86_64-cc:qxh0vyzccnfylmmc1f3bqpmi6k63smqz",
    },
)

platform(
    name = "ash-i686-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-i686-x86_64:d9s2p2bra9f0x8gjv23631p2ld9s1h9b",
    },
)

platform(
    name = "ash-i686-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-i686-x86_64-cc:w88vj7kk7an1r8d68as39gr24nxhgszv",
    },
)

platform(
    name = "ash-strace",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-strace:549hz3f6912z66pvm98nzqwgl6qxi246",
    },
)

platform(
    name = "ash-strace-coreutils",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-strace-coreutils:dsxpb02j6858d7rcfmn29nyzs5mfchmi",
    },
)

platform(
    name = "ash-strace-coreutils-i686",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-strace-coreutils-i686:cfx49c9lg8zg1k867sh8b9n4xyx7fn9m",
    },
)

platform(
    name = "ash-strace-coreutils-i686-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-strace-coreutils-i686-cc:lkcvg3xxs8jf2lgzjal0avy1il1vzh5m",
    },
)

platform(
    name = "ash-strace-coreutils-i686-cc-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-strace-coreutils-i686-cc-x86_64:p75j4hiljbwclzhzr6s382sr5vvxy6ix",
    },
)

platform(
    name = "ash-strace-coreutils-i686-cc-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-strace-coreutils-i686-cc-x86_64-cc:84czsnq9d2svj5kkqjzqa6aiw537w8r6",
    },
)

platform(
    name = "ash-strace-coreutils-i686-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-strace-coreutils-i686-x86_64:fyx88qpirr19q12yn2wp2svijx8n8yv3",
    },
)

platform(
    name = "ash-strace-coreutils-i686-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-strace-coreutils-i686-x86_64-cc:291pby1vm61s861nimnsjgqz3lx8r941",
    },
)

platform(
    name = "ash-strace-coreutils-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-strace-coreutils-x86_64:9nrkjhdlzwidpggi8j0y0kv8y447d9wk",
    },
)

platform(
    name = "ash-strace-coreutils-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-strace-coreutils-x86_64-cc:pv9jjkjh6pzkd1d0ds23xhzrrphsn5p3",
    },
)

platform(
    name = "ash-strace-i686",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-strace-i686:03a60xkfxibssxvd2xwd6y10kbmflwcc",
    },
)

platform(
    name = "ash-strace-i686-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-strace-i686-cc:p46k4lxlydq8w1w7jh5y9fisp31ib4wi",
    },
)

platform(
    name = "ash-strace-i686-cc-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-strace-i686-cc-x86_64:1fbmqlayvn894fi2y39f6ihc8kz54b5g",
    },
)

platform(
    name = "ash-strace-i686-cc-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-strace-i686-cc-x86_64-cc:vv7v50a20n21cm6dw1s7spf9aybvbsh6",
    },
)

platform(
    name = "ash-strace-i686-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-strace-i686-x86_64:sl6ldicn9vjcpzq4p1gwz154jv7s920z",
    },
)

platform(
    name = "ash-strace-i686-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-strace-i686-x86_64-cc:8yxawv2qkblxzgykk5yfaznhl8br3j8s",
    },
)

platform(
    name = "ash-strace-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-strace-x86_64:gil065mh7i9aqvrq6hpaxf960kxvfk5f",
    },
)

platform(
    name = "ash-strace-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-strace-x86_64-cc:mipid6rnnsjxc9y8780k7517kg79j9l6",
    },
)

platform(
    name = "ash-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-x86_64:fzvf5scwx3l5jdj86lwlfll9kwd6i4yy",
    },
)

platform(
    name = "ash-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-x86_64-cc:kx29mmmdv02yw9z9rzc1jm6z4b1darr5",
    },
)

platform(
    name = "bash",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash:ihn569dic2l4far92il87f6acc58vk8v",
    },
)

platform(
    name = "bash-coreutils",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-coreutils:jxpm1124r832f3qidv8yb042pdp0q50b",
    },
)

platform(
    name = "bash-coreutils-i686",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-coreutils-i686:kpb0n8nnrb6pzx6jc2xnsi6kynjqdgar",
    },
)

platform(
    name = "bash-coreutils-i686-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-coreutils-i686-cc:rzmsg6fam5z5yd9mxdmn7i3fvf7p8l5l",
    },
)

platform(
    name = "bash-coreutils-i686-cc-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-coreutils-i686-cc-x86_64:flk7q872vr40z21j2gc7gxfn3jhyf80n",
    },
)

platform(
    name = "bash-coreutils-i686-cc-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-coreutils-i686-cc-x86_64-cc:wldm2msknl2z2r00vipi703z0wxqji2c",
    },
)

platform(
    name = "bash-coreutils-i686-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-coreutils-i686-x86_64:nww54ivka5v6vy846av7gfb9z3axxd5s",
    },
)

platform(
    name = "bash-coreutils-i686-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-coreutils-i686-x86_64-cc:w75p0hmxw5rcjmx4qs2jylr1w10aqhx9",
    },
)

platform(
    name = "bash-coreutils-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-coreutils-x86_64:v1whzx1vvhab5dls70ihvhlgfzma6q5f",
    },
)

platform(
    name = "bash-coreutils-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-coreutils-x86_64-cc:4cl64a0g7sv4qhlj3xx5bs3mk4vvam18",
    },
)

platform(
    name = "bash-i686",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-i686:r3hky2pn8sdwj1ma1sb6aif7mhmrn9lh",
    },
)

platform(
    name = "bash-i686-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-i686-cc:b5vgp9ad32kvnk35jm4pk5iimm8v06ky",
    },
)

platform(
    name = "bash-i686-cc-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-i686-cc-x86_64:sns1da0p9kgvvg61qbjx49qfzx2mgyc4",
    },
)

platform(
    name = "bash-i686-cc-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-i686-cc-x86_64-cc:sd6bmd7c0cgcqzmdnrgwkv7qybpvwjpz",
    },
)

platform(
    name = "bash-i686-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-i686-x86_64:i6ppvzx7iwx2h1p5fr153j8lchaq57r1",
    },
)

platform(
    name = "bash-i686-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-i686-x86_64-cc:3n3sp47bs8l8cibk5grlhzjhpl96fnz4",
    },
)

platform(
    name = "bash-strace",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-strace:9z30ydwkf5y7xwls2awz1z4ybbgwzxg0",
    },
)

platform(
    name = "bash-strace-coreutils",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-strace-coreutils:mjhw4fmb25spd164skpas1ryl1a7kglg",
    },
)

platform(
    name = "bash-strace-coreutils-i686",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-strace-coreutils-i686:3x6ls77gkpr1c9fcc68zprrfmi0y98iy",
    },
)

platform(
    name = "bash-strace-coreutils-i686-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-strace-coreutils-i686-cc:6jjz7jja6c22pkc5577jjh3lr9mn0vwz",
    },
)

platform(
    name = "bash-strace-coreutils-i686-cc-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-strace-coreutils-i686-cc-x86_64:vyl2laywixym904ngdgdqwwfwn9ayaba",
    },
)

platform(
    name = "bash-strace-coreutils-i686-cc-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-strace-coreutils-i686-cc-x86_64-cc:fs9czszk82b1v9rci5d9486x3xqqpns6",
    },
)

platform(
    name = "bash-strace-coreutils-i686-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-strace-coreutils-i686-x86_64:58l9b3k353z30b36qbr0cvkfb58inyfq",
    },
)

platform(
    name = "bash-strace-coreutils-i686-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-strace-coreutils-i686-x86_64-cc:c4w6bwrf495xnad3fma44xg32wix62y1",
    },
)

platform(
    name = "bash-strace-coreutils-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-strace-coreutils-x86_64:zf5lacfa8icf9rpi8hb00vp50cimcxfr",
    },
)

platform(
    name = "bash-strace-coreutils-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-strace-coreutils-x86_64-cc:6jfi6al64cq2lxjpi30y53kvyk2glr9h",
    },
)

platform(
    name = "bash-strace-i686",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-strace-i686:j7fq31c8k3zmn67hv0imsz54x3lsqhg8",
    },
)

platform(
    name = "bash-strace-i686-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-strace-i686-cc:185k1ac134c54g1gd26qyi30mbbfxd92",
    },
)

platform(
    name = "bash-strace-i686-cc-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-strace-i686-cc-x86_64:2f49qc3s0qp33azvwgjacr7cwqn23hd9",
    },
)

platform(
    name = "bash-strace-i686-cc-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-strace-i686-cc-x86_64-cc:436y4x2psaq5p9rkwzsw877rsfg7biqp",
    },
)

platform(
    name = "bash-strace-i686-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-strace-i686-x86_64:adkhc4k9bpwsn0qh6zsbb52cks27bca2",
    },
)

platform(
    name = "bash-strace-i686-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-strace-i686-x86_64-cc:xz9pk9b1zicfpbcb0hr345k48b44n4g6",
    },
)

platform(
    name = "bash-strace-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-strace-x86_64:zz2jb479hjscbrnygikjc0ldvvln2nns",
    },
)

platform(
    name = "bash-strace-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-strace-x86_64-cc:0qpp16bna37gnaci51q95hma78hg8wkd",
    },
)

platform(
    name = "bash-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-x86_64:4xihrhaircd16ma0mr7sdjvqpccijwam",
    },
)

platform(
    name = "bash-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-x86_64-cc:y6pmz4gi2vkw5yyh1v6gyfw9dalma6gm",
    },
)

platform(
    name = "coreutils",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/coreutils:q3jy136p4dggar6vq09vwkkcvbin3h92",
    },
)

platform(
    name = "coreutils-i686",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/coreutils-i686:q61z926may94z95gwhgmf9f0av73gjck",
    },
)

platform(
    name = "coreutils-i686-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/coreutils-i686-cc:gaq6cymx4agrw16l48r6kccrs45k3dhi",
    },
)

platform(
    name = "coreutils-i686-cc-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/coreutils-i686-cc-x86_64:p0nifx4i97fh62i7qchr3akhanxyd62s",
    },
)

platform(
    name = "coreutils-i686-cc-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/coreutils-i686-cc-x86_64-cc:s0npl326wsdhpjh2vvys34274swmvg0w",
    },
)

platform(
    name = "coreutils-i686-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/coreutils-i686-x86_64:3f1zcpmv3jnjhmcv3ndswnhrllzayvg7",
    },
)

platform(
    name = "coreutils-i686-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/coreutils-i686-x86_64-cc:310gl59f2myrx35zhpn51s2w3wmndkh6",
    },
)

platform(
    name = "coreutils-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/coreutils-x86_64:ik48b2yxr6n6dmc698xgfvd1nny02amm",
    },
)

platform(
    name = "coreutils-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/coreutils-x86_64-cc:r0id7s1f88vms1h0dfc2c7s1hyf0jl1q",
    },
)

platform(
    name = "i686",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/i686:0jskpj2163r1iznrrjwnk208hfixb9zl",
    },
)

platform(
    name = "i686-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/i686-cc:92y5ic2r446qsj3b6nvc3ir04wlm98zh",
    },
)

platform(
    name = "i686-cc-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/i686-cc-x86_64:f1g0c61fwz25hfv76fhr7lbp345z2fqz",
    },
)

platform(
    name = "i686-cc-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/i686-cc-x86_64-cc:ninqa8xhajsdm6y2dwkh9pygijk76mf8",
    },
)

platform(
    name = "i686-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/i686-x86_64:vx1ai8ia8q8saah19d166npl5qv19kvr",
    },
)

platform(
    name = "i686-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/i686-x86_64-cc:wap0zxd94anvb04arc23al4y9lgi962r",
    },
)

platform(
    name = "strace",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/strace:3rxv91s9ynzfjw3imn09wzbb7bbmggd3",
    },
)

platform(
    name = "strace-coreutils",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/strace-coreutils:0r680a0akmza136nir85f5rah4hnbs9s",
    },
)

platform(
    name = "strace-coreutils-i686",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/strace-coreutils-i686:zzmnzzixj4lkyhcx5yg9axl0hra3ijiv",
    },
)

platform(
    name = "strace-coreutils-i686-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/strace-coreutils-i686-cc:dnrc9jd2hy8n7k95ssykvypk4dy46xya",
    },
)

platform(
    name = "strace-coreutils-i686-cc-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/strace-coreutils-i686-cc-x86_64:81d9dcw3ni9jqa8wr4mv2nlqnv4zil1g",
    },
)

platform(
    name = "strace-coreutils-i686-cc-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/strace-coreutils-i686-cc-x86_64-cc:450kvzzvkhrv9zfi1iph19gh139hrbxg",
    },
)

platform(
    name = "strace-coreutils-i686-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/strace-coreutils-i686-x86_64:wv9690dn1dmmydg758qj6lkbll4vc6sj",
    },
)

platform(
    name = "strace-coreutils-i686-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/strace-coreutils-i686-x86_64-cc:0kdhcs9snqc85awb733szp3l7ksfy98r",
    },
)

platform(
    name = "strace-coreutils-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/strace-coreutils-x86_64:n3q6198rfddxls8673x9jnmdbzjik1mj",
    },
)

platform(
    name = "strace-coreutils-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/strace-coreutils-x86_64-cc:1wm1xmppbhmqapjjjd886ncdzf2hd85h",
    },
)

platform(
    name = "strace-i686",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/strace-i686:p2nm2rwx4fbmv8b7fm4mj68n1mv18mvd",
    },
)

platform(
    name = "strace-i686-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/strace-i686-cc:axiiys271lb78d0yrx209j3l2ki2i286",
    },
)

platform(
    name = "strace-i686-cc-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/strace-i686-cc-x86_64:wj0irmhzclnqfig5yjr8wqravrk1xbqi",
    },
)

platform(
    name = "strace-i686-cc-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/strace-i686-cc-x86_64-cc:dmcv6nk8p6bj4fg3rbijnidxyfn19r38",
    },
)

platform(
    name = "strace-i686-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/strace-i686-x86_64:z5r4h9da3mqrkl5vi9w15pq1ilks8z9q",
    },
)

platform(
    name = "strace-i686-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/strace-i686-x86_64-cc:fxg4afhnmqkanj9hnx5biqghd0kxml2z",
    },
)

platform(
    name = "strace-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/strace-x86_64:kdpgbc9camacb7v1nn5xwizbnkhjnwyx",
    },
)

platform(
    name = "strace-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/strace-x86_64-cc:l6z6y3fz0pjy8dvj2w7klwxnmzz5niz3",
    },
)

platform(
    name = "x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/x86_64:a5760mg4awxg7h351xdkln286r1hxxxz",
    },
)

platform(
    name = "x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/x86_64-cc:z9wzvmbsvg6mjhcb84b2lwh8n5x33qhz",
    },
)

