""" Starterkit flavors in form of Bazel execution platforms. """

package(default_visibility = ["//visibility:public"])

# Anything falling in this category should not execute
platform(name = "DEV_NULL_PLATFORM")

platform(
    name = "starterkit-x86_64-linux",
    constraint_values = [
        "@platforms//os:linux",
        "@platforms//cpu:x86_64",
    ],
    exec_properties = {
        "OSFamily": "Linux",
    },
)

# Please be aware,
# that you should select only ONE
# of the following platforms to be registered,
# or add more specific constraints.

platform(
    name = "ash",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash:qy7zyd1fdajgcgknnwmpb4v0gfg119fa",
    },
)

platform(
    name = "ash-bash",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash:av5022vv36639z4rx3y556s9bwc0zakq",
    },
)

platform(
    name = "ash-bash-coreutils",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-coreutils:kvw5mfpzrz33qim734swxnpqa1gcl9kb",
    },
)

platform(
    name = "ash-bash-coreutils-i686",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-coreutils-i686:z2i12qv8m2cx2234gg9mnji995bpai8b",
    },
)

platform(
    name = "ash-bash-coreutils-i686-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-coreutils-i686-cc:icw59f0pwjq9i5ab6ynfl0s36fj9d9sk",
    },
)

platform(
    name = "ash-bash-coreutils-i686-cc-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-coreutils-i686-cc-x86_64:wvdsylg7f149k4lbbdk8fvnajfi0729q",
    },
)

platform(
    name = "ash-bash-coreutils-i686-cc-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-coreutils-i686-cc-x86_64-cc:ic6angvicd5kcasd286ba3iwaswbhkpn",
    },
)

platform(
    name = "ash-bash-coreutils-i686-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-coreutils-i686-x86_64:c90clxnya67mjvqawc3kgqsx4xr5x5s4",
    },
)

platform(
    name = "ash-bash-coreutils-i686-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-coreutils-i686-x86_64-cc:06yd6l1lsxik5a8qzs02h0kl7l92q7g0",
    },
)

platform(
    name = "ash-bash-coreutils-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-coreutils-x86_64:a1zv5a8nbhfgd4l0kkcliyw6yx0l2ws6",
    },
)

platform(
    name = "ash-bash-coreutils-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-coreutils-x86_64-cc:s6d7clwmq0nbwwbs096abr3l8kaslhgp",
    },
)

platform(
    name = "ash-bash-i686",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-i686:qwyhj389zhhw35gkpad1y78k1v691nx7",
    },
)

platform(
    name = "ash-bash-i686-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-i686-cc:g12745x7hzxkddx7psvaa3lkr08pa1d2",
    },
)

platform(
    name = "ash-bash-i686-cc-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-i686-cc-x86_64:68m3gy1llqjw20gc3dx4aqnmkflksnz4",
    },
)

platform(
    name = "ash-bash-i686-cc-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-i686-cc-x86_64-cc:5zq1mwd0lrbsx38q46rxy4ajl28cvv9s",
    },
)

platform(
    name = "ash-bash-i686-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-i686-x86_64:md3k4m1lz8854idiwj6yng52i9rhrjg2",
    },
)

platform(
    name = "ash-bash-i686-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-i686-x86_64-cc:2mgy8fjqhjmybnws3qsnwp3lz34s6nmw",
    },
)

platform(
    name = "ash-bash-strace",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-strace:cc75626cg6d96d4378zskv5gwkkh7jd5",
    },
)

platform(
    name = "ash-bash-strace-coreutils",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-strace-coreutils:xy1vq81mbvdarzyqvp0j2g6kapbqznqp",
    },
)

platform(
    name = "ash-bash-strace-coreutils-i686",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-strace-coreutils-i686:77s6fbw1b3m69g0j8s34f6pms5l3cvk8",
    },
)

platform(
    name = "ash-bash-strace-coreutils-i686-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-strace-coreutils-i686-cc:hr1fcdi8kgia8b58n0ar7mhgq78zj4bp",
    },
)

platform(
    name = "ash-bash-strace-coreutils-i686-cc-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-strace-coreutils-i686-cc-x86_64:v6x5c4yr3qiw0hpqa5s79zl164axhfc7",
    },
)

platform(
    name = "ash-bash-strace-coreutils-i686-cc-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-strace-coreutils-i686-cc-x86_64-cc:bfnqhz151wq0yszczsgn5224kajmm3qf",
    },
)

platform(
    name = "ash-bash-strace-coreutils-i686-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-strace-coreutils-i686-x86_64:6dk76nl17h04a49mpx6zan43nzlmzdqx",
    },
)

platform(
    name = "ash-bash-strace-coreutils-i686-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-strace-coreutils-i686-x86_64-cc:knx5cbslnl8c8bpv6cswdgkvnvivv854",
    },
)

platform(
    name = "ash-bash-strace-coreutils-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-strace-coreutils-x86_64:7yrlmn0j205ahpm7njxpfjfzq1qb06z1",
    },
)

platform(
    name = "ash-bash-strace-coreutils-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-strace-coreutils-x86_64-cc:pz5895m8d8f0if3gc5grp8wlbsc8mcmy",
    },
)

platform(
    name = "ash-bash-strace-i686",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-strace-i686:awrp1p196nffp8xc39aaqn3dm9wx2gxg",
    },
)

platform(
    name = "ash-bash-strace-i686-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-strace-i686-cc:mp7xm1j6xcpxdbc23nxhj3g6vrhylxf3",
    },
)

platform(
    name = "ash-bash-strace-i686-cc-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-strace-i686-cc-x86_64:jjpaxjhb7dm77n0clal62l49p9j525h1",
    },
)

platform(
    name = "ash-bash-strace-i686-cc-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-strace-i686-cc-x86_64-cc:jw7h9xb81hwxc9fw04gp14jxd85fn4lc",
    },
)

platform(
    name = "ash-bash-strace-i686-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-strace-i686-x86_64:k2zcazlh2h9g00c70qrvriracdm0gmsd",
    },
)

platform(
    name = "ash-bash-strace-i686-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-strace-i686-x86_64-cc:k7x5bq45hbdd620g2srkzp56q197l4vk",
    },
)

platform(
    name = "ash-bash-strace-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-strace-x86_64:70jvsnxqi81diwhn35h8h9jnlv096f0b",
    },
)

platform(
    name = "ash-bash-strace-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-strace-x86_64-cc:75mhm2lap4zmgsjmb8w2202y0v6gv4db",
    },
)

platform(
    name = "ash-bash-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-x86_64:bdizfyp54py2zyza0g97sb83rnmrddhl",
    },
)

platform(
    name = "ash-bash-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-bash-x86_64-cc:w7ixc4qak8h87ia5giandha1v9nw39dl",
    },
)

platform(
    name = "ash-coreutils",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-coreutils:k360f6mpinwfcagx1q6aj6g05w932fv1",
    },
)

platform(
    name = "ash-coreutils-i686",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-coreutils-i686:4djqp7as1dwz4mz14xw96l1azdwrpdnn",
    },
)

platform(
    name = "ash-coreutils-i686-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-coreutils-i686-cc:7sv95pmd6scrjwgpj915k1p0gw5zrgv1",
    },
)

platform(
    name = "ash-coreutils-i686-cc-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-coreutils-i686-cc-x86_64:mrsf88fg3ggy9cjjkayingaqngh2jjmb",
    },
)

platform(
    name = "ash-coreutils-i686-cc-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-coreutils-i686-cc-x86_64-cc:pg9jyg5mi7l1x1ibw3gl2z1h61sfvdwd",
    },
)

platform(
    name = "ash-coreutils-i686-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-coreutils-i686-x86_64:gj2xxwazmmjphz04bpqbvj8jsvn6g9hf",
    },
)

platform(
    name = "ash-coreutils-i686-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-coreutils-i686-x86_64-cc:sg1s7hk994a6ca639ymdlpkxjhnxf4ki",
    },
)

platform(
    name = "ash-coreutils-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-coreutils-x86_64:a36k4bcknm9vj3v5v0wx5i91vq0nm407",
    },
)

platform(
    name = "ash-coreutils-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-coreutils-x86_64-cc:6mn8dialnzp2rif96kfrkkzaraa1ghqg",
    },
)

platform(
    name = "ash-i686",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-i686:188b84qa4db6zyhwpi14lvm3x1h39777",
    },
)

platform(
    name = "ash-i686-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-i686-cc:4573vd5bzf7mm89zaj64i1g6jsz8gfbr",
    },
)

platform(
    name = "ash-i686-cc-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-i686-cc-x86_64:gfhr75hfc78lj0s2snvkz0ixmjhi1icg",
    },
)

platform(
    name = "ash-i686-cc-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-i686-cc-x86_64-cc:7pc3d081wzi9k27xv3gc1sw7ir3d0396",
    },
)

platform(
    name = "ash-i686-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-i686-x86_64:wjjpal0yvm8m02j0wc737pr0izjrwkgn",
    },
)

platform(
    name = "ash-i686-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-i686-x86_64-cc:3bllaqx3gvmhp606q9c66265cddg0ywl",
    },
)

platform(
    name = "ash-strace",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-strace:nkzy8zy87vwaghiha96y7r1af72s4rwr",
    },
)

platform(
    name = "ash-strace-coreutils",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-strace-coreutils:p44fkyksiipj5p83c2nicb3a5ba0kz50",
    },
)

platform(
    name = "ash-strace-coreutils-i686",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-strace-coreutils-i686:xvcjn6hx9x9wnkbcwqwv3fzzxq633k55",
    },
)

platform(
    name = "ash-strace-coreutils-i686-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-strace-coreutils-i686-cc:7q7r6sr9yixw3f09cdsmc35x6a6863dv",
    },
)

platform(
    name = "ash-strace-coreutils-i686-cc-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-strace-coreutils-i686-cc-x86_64:4bb6hcivv1gwmcrf43kmdac5gfrmmifi",
    },
)

platform(
    name = "ash-strace-coreutils-i686-cc-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-strace-coreutils-i686-cc-x86_64-cc:gas6xqs5vc7h17vkg3k2y1x1brpk1nz8",
    },
)

platform(
    name = "ash-strace-coreutils-i686-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-strace-coreutils-i686-x86_64:d37di680jrda9f6c5ii6qc0d2n641qmc",
    },
)

platform(
    name = "ash-strace-coreutils-i686-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-strace-coreutils-i686-x86_64-cc:5h72nms7hvl251ygkcrprapwwlclihrp",
    },
)

platform(
    name = "ash-strace-coreutils-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-strace-coreutils-x86_64:58bg4wk8w5qs8s7av5w69a5c6ixzkajz",
    },
)

platform(
    name = "ash-strace-coreutils-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-strace-coreutils-x86_64-cc:s39jya0cb3bgfj5gnbxxnd5bhmfg4my6",
    },
)

platform(
    name = "ash-strace-i686",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-strace-i686:l7wzlcy4c00h1rpa9lxy3zdrsqq9xbbq",
    },
)

platform(
    name = "ash-strace-i686-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-strace-i686-cc:zbmic1hf487hlnf59p8rwcgijg8ijkbv",
    },
)

platform(
    name = "ash-strace-i686-cc-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-strace-i686-cc-x86_64:pkc4qd00bm0kz40457zk56hndc1c8my6",
    },
)

platform(
    name = "ash-strace-i686-cc-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-strace-i686-cc-x86_64-cc:s1zk3ma66kj7d1avmc01b6j7qafg4idm",
    },
)

platform(
    name = "ash-strace-i686-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-strace-i686-x86_64:17i2nqac27bixh7qbdjkh1fqgkwva8ni",
    },
)

platform(
    name = "ash-strace-i686-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-strace-i686-x86_64-cc:z6gc02f1nq4gln00bb6xx2z9rxblhffk",
    },
)

platform(
    name = "ash-strace-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-strace-x86_64:y0rsfdy54kw7vk0ldy0fm457jqpyr0dw",
    },
)

platform(
    name = "ash-strace-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-strace-x86_64-cc:c4bqkmsi72b503h34q53y6kcn1h27rn4",
    },
)

platform(
    name = "ash-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-x86_64:qfif9kzhv5z2zq97n89c6f6xni2p8pmj",
    },
)

platform(
    name = "ash-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/ash-x86_64-cc:a1hap5d1s0x1vf5a4fhx309c64ahkfwx",
    },
)

platform(
    name = "bash",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash:3f5fqwy6nwvcfs55bwbhh4vw3yhgbp3m",
    },
)

platform(
    name = "bash-coreutils",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-coreutils:yhgkyn71g3a38v3zsnaj5c6da4qsq27h",
    },
)

platform(
    name = "bash-coreutils-i686",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-coreutils-i686:4z90jw8k0dqywizs7sn87jf9bn56s6wf",
    },
)

platform(
    name = "bash-coreutils-i686-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-coreutils-i686-cc:9k2lxcg80hddm4dw6g1g02gw79wm3ddd",
    },
)

platform(
    name = "bash-coreutils-i686-cc-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-coreutils-i686-cc-x86_64:6lg1ps4hg5c5726li28xvnsxc1yfgjkh",
    },
)

platform(
    name = "bash-coreutils-i686-cc-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-coreutils-i686-cc-x86_64-cc:8254s5ybmyrxxbh97chh78s3sg7vslhn",
    },
)

platform(
    name = "bash-coreutils-i686-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-coreutils-i686-x86_64:hyj4n82nbcii48jjh9vx9n0l8qnnl2cb",
    },
)

platform(
    name = "bash-coreutils-i686-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-coreutils-i686-x86_64-cc:nifhxyhmms1alf6khfshncj9r0990fag",
    },
)

platform(
    name = "bash-coreutils-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-coreutils-x86_64:n3hnbnsr2ljaxz8k0iipa3bi7x0q675d",
    },
)

platform(
    name = "bash-coreutils-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-coreutils-x86_64-cc:x1szrix9h4md71acw8l9pxx0q550axa8",
    },
)

platform(
    name = "bash-i686",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-i686:zgjnhjiw3yk4znc925044lcfgyzz42vy",
    },
)

platform(
    name = "bash-i686-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-i686-cc:ygkkk4260vhq2xyzbsys416hphyyblni",
    },
)

platform(
    name = "bash-i686-cc-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-i686-cc-x86_64:ljw7af0p7f1xwvv1mj0f231xb0rnklmc",
    },
)

platform(
    name = "bash-i686-cc-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-i686-cc-x86_64-cc:zx4nm88jfnp35kgmk36w4nvxnb3z1hl9",
    },
)

platform(
    name = "bash-i686-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-i686-x86_64:21nwggfxjy9n1ssyyrvf87jl1nrss20f",
    },
)

platform(
    name = "bash-i686-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-i686-x86_64-cc:wghsrv2kn5k2wji32wnlymm46fa9vn5s",
    },
)

platform(
    name = "bash-strace",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-strace:lxqmb60ag8k7gbwizk9y49sjrpapj7dj",
    },
)

platform(
    name = "bash-strace-coreutils",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-strace-coreutils:jmbc69nyxnsbkn02rjkgr6xd2apiax81",
    },
)

platform(
    name = "bash-strace-coreutils-i686",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-strace-coreutils-i686:wpyncl86qnrfbr56c4vv1s6dr38xl9z8",
    },
)

platform(
    name = "bash-strace-coreutils-i686-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-strace-coreutils-i686-cc:9rb8pcdxpabv4pmvkv9hqzi2bi9z8z57",
    },
)

platform(
    name = "bash-strace-coreutils-i686-cc-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-strace-coreutils-i686-cc-x86_64:cyiq1xj3gb0l94msamlypxj5nb9b62nw",
    },
)

platform(
    name = "bash-strace-coreutils-i686-cc-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-strace-coreutils-i686-cc-x86_64-cc:kmzy2zrj776lh091x3ml3p7sywb1cn60",
    },
)

platform(
    name = "bash-strace-coreutils-i686-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-strace-coreutils-i686-x86_64:nkvqjhklqc9c4ynb68ng55fljgzp8yij",
    },
)

platform(
    name = "bash-strace-coreutils-i686-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-strace-coreutils-i686-x86_64-cc:0xr2w52rl6l10rbyx7pddmg5d8nbz3sy",
    },
)

platform(
    name = "bash-strace-coreutils-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-strace-coreutils-x86_64:nya5rj0nrbd4zkihqk20q6h8fs8diy57",
    },
)

platform(
    name = "bash-strace-coreutils-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-strace-coreutils-x86_64-cc:3pbjdi39h7y8nsrmprcifp15dkrdq54n",
    },
)

platform(
    name = "bash-strace-i686",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-strace-i686:4n6jar5ailaq1n6zhg93x8dcycg5jns4",
    },
)

platform(
    name = "bash-strace-i686-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-strace-i686-cc:qsnxg0qz65791w6rv5q5bfzyavyg86wy",
    },
)

platform(
    name = "bash-strace-i686-cc-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-strace-i686-cc-x86_64:14h1qpfvdqj29k6hczrdgh8ai10fyw01",
    },
)

platform(
    name = "bash-strace-i686-cc-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-strace-i686-cc-x86_64-cc:b7fa0bhpzwbn6nfnkbgny95dcly4rl2m",
    },
)

platform(
    name = "bash-strace-i686-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-strace-i686-x86_64:3qilidwiabzz9s56bysmcaqnydr6nyd2",
    },
)

platform(
    name = "bash-strace-i686-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-strace-i686-x86_64-cc:vladn87s1wyj0v4pd3ja1zmcx8rdpwki",
    },
)

platform(
    name = "bash-strace-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-strace-x86_64:sjb0vk3parrkqlfjh6p5l5jpd22n6izx",
    },
)

platform(
    name = "bash-strace-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-strace-x86_64-cc:08gci34z5jvhjjzhhrx9d7cv96kl617a",
    },
)

platform(
    name = "bash-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-x86_64:l8jpfyxz5s8xk2wzpcs1bfppfy9zk9ri",
    },
)

platform(
    name = "bash-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/bash-x86_64-cc:znnr05lifda9n24w7ra68sv3hpgfnjkw",
    },
)

platform(
    name = "coreutils",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/coreutils:7azvxl38fr7f6grz7mgys4v1qr52clvd",
    },
)

platform(
    name = "coreutils-i686",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/coreutils-i686:cqnkamqv27swyvb4ndz31cpx4g5vlsyq",
    },
)

platform(
    name = "coreutils-i686-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/coreutils-i686-cc:pgafsrsrjd4r5zqb6xpi95a5lpcjdik1",
    },
)

platform(
    name = "coreutils-i686-cc-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/coreutils-i686-cc-x86_64:pw78bqxx38pc1d3jxw20mry1h4jirkm0",
    },
)

platform(
    name = "coreutils-i686-cc-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/coreutils-i686-cc-x86_64-cc:jxa6k87gm57w33lrwxcw0aydnl97fly3",
    },
)

platform(
    name = "coreutils-i686-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/coreutils-i686-x86_64:0z203228bmh3dgnb9bqs71jr14lhf2aa",
    },
)

platform(
    name = "coreutils-i686-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/coreutils-i686-x86_64-cc:a9p2qdy2m8cqypvp9chxw2zwi0w9qybf",
    },
)

platform(
    name = "coreutils-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/coreutils-x86_64:vsxax39zl87kv7d01wjvkj4lffay30nh",
    },
)

platform(
    name = "coreutils-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/coreutils-x86_64-cc:yp7ddwg22bdl9axnma82dv8g4i965sjl",
    },
)

platform(
    name = "i686",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/i686:nmg7fc39wv7if7yg044c9mzlw6jpf71q",
    },
)

platform(
    name = "i686-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/i686-cc:00650nbqs61d1la4szckqrw3am8x8631",
    },
)

platform(
    name = "i686-cc-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/i686-cc-x86_64:nrgbqj9m2pjjs5pdadlk8w4kb9s8i8q2",
    },
)

platform(
    name = "i686-cc-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/i686-cc-x86_64-cc:3bwblc7vmg8q4s4ysfxj037nxk4zpv30",
    },
)

platform(
    name = "i686-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/i686-x86_64:5ah9ac4h0mkqcdq1zqc4mnjw6lay63y1",
    },
)

platform(
    name = "i686-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/i686-x86_64-cc:6w4yr0di5yl0yzkwiz0v1pfd22qibprh",
    },
)

platform(
    name = "strace",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/strace:cv6basw026290hf8d088kig124aqpwwf",
    },
)

platform(
    name = "strace-coreutils",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/strace-coreutils:6hl35qc3ak8jmslyhmzv7wr4q0kdl915",
    },
)

platform(
    name = "strace-coreutils-i686",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/strace-coreutils-i686:wlbgrsvfy0lfxsmar8bx79sdar4wgbgd",
    },
)

platform(
    name = "strace-coreutils-i686-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/strace-coreutils-i686-cc:jywk9rdm2k86r07v9axv6s1xj0rp2lxd",
    },
)

platform(
    name = "strace-coreutils-i686-cc-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/strace-coreutils-i686-cc-x86_64:4pk8rq5y271nwbrrm6h7nc9y9jlnrdbw",
    },
)

platform(
    name = "strace-coreutils-i686-cc-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/strace-coreutils-i686-cc-x86_64-cc:bf3zy04c2k6myibj39j0j70kmqbmk717",
    },
)

platform(
    name = "strace-coreutils-i686-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/strace-coreutils-i686-x86_64:k84bj2p48527yrlzgx5zwkblvxza0fjb",
    },
)

platform(
    name = "strace-coreutils-i686-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/strace-coreutils-i686-x86_64-cc:svhcwvan5lhz1di0f0y4wgmvxxk6fqmc",
    },
)

platform(
    name = "strace-coreutils-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/strace-coreutils-x86_64:qpna4kmx49cd8ij5mbzi39c4dxlwv9y5",
    },
)

platform(
    name = "strace-coreutils-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/strace-coreutils-x86_64-cc:0zky2q3lzfr5kqc10fz9s18j6rpb4dkf",
    },
)

platform(
    name = "strace-i686",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/strace-i686:dl03cj2j02w57jy8xfcz0bxajm7vply9",
    },
)

platform(
    name = "strace-i686-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/strace-i686-cc:dc8rv70rgv417m2mlaqsp0376p902ffn",
    },
)

platform(
    name = "strace-i686-cc-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/strace-i686-cc-x86_64:1ypl5rkibqwd5dsambxv97y9haid7kv3",
    },
)

platform(
    name = "strace-i686-cc-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/strace-i686-cc-x86_64-cc:fkdiyx41ch7rig4hvydq78hzp2v9b8vh",
    },
)

platform(
    name = "strace-i686-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/strace-i686-x86_64:7rg07vkjl7ild8i0z4whr75sbjsml9zp",
    },
)

platform(
    name = "strace-i686-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/strace-i686-x86_64-cc:210q8j4yyn35inrrbfxikmsd3dma4f1q",
    },
)

platform(
    name = "strace-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/strace-x86_64:gdmydkhypb8g97qp71a3nkngb3ddcc8y",
    },
)

platform(
    name = "strace-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/strace-x86_64-cc:n40485hgbcjl2v5kg8k2clyp09qjk4xs",
    },
)

platform(
    name = "x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/x86_64:cawbsqx1q5izqiqrwad9x3bahwrisb9a",
    },
)

platform(
    name = "x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.apps.morrigna.rules-nix.build/explore-bzl/x86_64-cc:9pn62jvc46dqs5nligi5xb6gswgrlv4v",
    },
)

