""" Starterkit flavors in form of Bazel execution platforms. """

package(default_visibility = ["//visibility:public"])

# Anything falling in this category should not execute
platform(name = "DEV_NULL_PLATFORM")

platform(
    name = "starterkit-x86_64-linux",
    constraint_values = [
        "@platforms//os:linux",
        "@platforms//cpu:x86_64",
    ],
    exec_properties = {
        "OSFamily": "Linux",
    },
)

# Please be aware,
# that you should select only ONE
# of the following platforms to be registered,
# or add more specific constraints.

platform(
    name = "ash",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash:fd20kbbbywiih422ki32lwh6nkfnfgl7",
    },
)

platform(
    name = "ash-bash",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-bash:0xvz0svnlvnvdykbm1apnyx8gcba9443",
    },
)

platform(
    name = "ash-bash-coreutils",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-bash-coreutils:8ggnsw49n873ihz3w3ga4k8glhrx15nk",
    },
)

platform(
    name = "ash-bash-coreutils-i686",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-bash-coreutils-i686:isvn5vhdll1wdvfb7ljfmllqnrybm36v",
    },
)

platform(
    name = "ash-bash-coreutils-i686-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-bash-coreutils-i686-cc:gw9k9282bkqh8fawr42jc3lcnkvl93z4",
    },
)

platform(
    name = "ash-bash-coreutils-i686-cc-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-bash-coreutils-i686-cc-x86_64:pkhm5krkciiqdw94ms32xwbp4jgh09fc",
    },
)

platform(
    name = "ash-bash-coreutils-i686-cc-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-bash-coreutils-i686-cc-x86_64-cc:bgps70x1w9pqcg6hl4yj0gapnb4542bn",
    },
)

platform(
    name = "ash-bash-coreutils-i686-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-bash-coreutils-i686-x86_64:yqx327izwj7ax71q1pdljzqn8dzl9ppr",
    },
)

platform(
    name = "ash-bash-coreutils-i686-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-bash-coreutils-i686-x86_64-cc:11pcyb7g29jah6qif1dqfvf3014rfzc6",
    },
)

platform(
    name = "ash-bash-coreutils-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-bash-coreutils-x86_64:wndpwfc55syw3b984ncay9rcs144v3lh",
    },
)

platform(
    name = "ash-bash-coreutils-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-bash-coreutils-x86_64-cc:0500q1z1ymxza9i95zd7xnihp340np79",
    },
)

platform(
    name = "ash-bash-i686",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-bash-i686:ynq82sqbkrxmrvc6rnpmw6562njcmc88",
    },
)

platform(
    name = "ash-bash-i686-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-bash-i686-cc:qcqhhvv7qc93xshnxbw7f82r7ksr6q83",
    },
)

platform(
    name = "ash-bash-i686-cc-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-bash-i686-cc-x86_64:vcyg5k582506fiibvab7vfp6pxm8j0i5",
    },
)

platform(
    name = "ash-bash-i686-cc-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-bash-i686-cc-x86_64-cc:q6bx4g5bszmb5g0a5fy1rzr0rcr2c906",
    },
)

platform(
    name = "ash-bash-i686-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-bash-i686-x86_64:036yzblw3vbdfqz30kpaiirzg76zw5qn",
    },
)

platform(
    name = "ash-bash-i686-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-bash-i686-x86_64-cc:73n4mrhxg78k95xra4050i9kvhss16hx",
    },
)

platform(
    name = "ash-bash-strace",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-bash-strace:fd0jxfjp7k9qb9m759wbf3npqrnsgxmz",
    },
)

platform(
    name = "ash-bash-strace-coreutils",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-bash-strace-coreutils:ack82k64v0kha0ahkg35yj000as34mrv",
    },
)

platform(
    name = "ash-bash-strace-coreutils-i686",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-bash-strace-coreutils-i686:6v41njxpcb6nspgzh0l56ff5kfcnvy6f",
    },
)

platform(
    name = "ash-bash-strace-coreutils-i686-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-bash-strace-coreutils-i686-cc:ypsl4q9v07w1nnf6s1yyap4mxl6ym949",
    },
)

platform(
    name = "ash-bash-strace-coreutils-i686-cc-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-bash-strace-coreutils-i686-cc-x86_64:m2kzn3kg9xd08wl87sxcim3q6qvh99li",
    },
)

platform(
    name = "ash-bash-strace-coreutils-i686-cc-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-bash-strace-coreutils-i686-cc-x86_64-cc:fhqmliwijlkbfzpj42ynas5njrfshzki",
    },
)

platform(
    name = "ash-bash-strace-coreutils-i686-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-bash-strace-coreutils-i686-x86_64:i4xdyf3m2f1g385alqx50i03rvj2gp68",
    },
)

platform(
    name = "ash-bash-strace-coreutils-i686-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-bash-strace-coreutils-i686-x86_64-cc:da9wls76s3x8rkisrcnw4zzfcais8l36",
    },
)

platform(
    name = "ash-bash-strace-coreutils-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-bash-strace-coreutils-x86_64:7spmha2bzjb8rf6aard1rwn4b7xq3mdr",
    },
)

platform(
    name = "ash-bash-strace-coreutils-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-bash-strace-coreutils-x86_64-cc:3c3ry2x56znb3ig4xfqab26x99h85hjx",
    },
)

platform(
    name = "ash-bash-strace-i686",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-bash-strace-i686:zjrj2l8ji0yhh8mbspa62c76n3ngq6qg",
    },
)

platform(
    name = "ash-bash-strace-i686-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-bash-strace-i686-cc:3vw3ygb4x65d20fymilg1apyblvk54ll",
    },
)

platform(
    name = "ash-bash-strace-i686-cc-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-bash-strace-i686-cc-x86_64:cny6vz6kf4gcxi61iyahxbkxszkj889y",
    },
)

platform(
    name = "ash-bash-strace-i686-cc-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-bash-strace-i686-cc-x86_64-cc:w790bx47qwppcap9lzzfy4jyhlpad4ap",
    },
)

platform(
    name = "ash-bash-strace-i686-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-bash-strace-i686-x86_64:a3fc5hsxj69d1x16mcpyn3k8d2s92lj6",
    },
)

platform(
    name = "ash-bash-strace-i686-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-bash-strace-i686-x86_64-cc:f4lm8krv8jhn8s8i6bxdqbnc1na7aq65",
    },
)

platform(
    name = "ash-bash-strace-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-bash-strace-x86_64:idrvlkkmns7lkf11sn9l31lgjg7dacx1",
    },
)

platform(
    name = "ash-bash-strace-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-bash-strace-x86_64-cc:x5l5qd7j53q38hzn2h4m19pqii722n0q",
    },
)

platform(
    name = "ash-bash-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-bash-x86_64:l38wyss4dclcn3nyrak18a425p2xavjp",
    },
)

platform(
    name = "ash-bash-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-bash-x86_64-cc:hgpqx2s1smkid94dqh9qqlfcmpxf631y",
    },
)

platform(
    name = "ash-coreutils",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-coreutils:hk8kxhbvw4818pblpdk81b4lb3pg5dr5",
    },
)

platform(
    name = "ash-coreutils-i686",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-coreutils-i686:nzj4i99y8hzc70wx150s94d4l4nmdvld",
    },
)

platform(
    name = "ash-coreutils-i686-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-coreutils-i686-cc:4rc7zwa2mr0g4is2q052ia42lm0gzm8m",
    },
)

platform(
    name = "ash-coreutils-i686-cc-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-coreutils-i686-cc-x86_64:43q279ygxim8s1j67wxv7a7kyrzh50di",
    },
)

platform(
    name = "ash-coreutils-i686-cc-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-coreutils-i686-cc-x86_64-cc:qkzjn0nyj6j7f72q4hsgily8i0l9mwqs",
    },
)

platform(
    name = "ash-coreutils-i686-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-coreutils-i686-x86_64:ywn0q2xz8wnakkapgmci88nncyadrz4n",
    },
)

platform(
    name = "ash-coreutils-i686-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-coreutils-i686-x86_64-cc:3k7lha7sa1v6xba9i2q088dr2dbqvh25",
    },
)

platform(
    name = "ash-coreutils-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-coreutils-x86_64:7sw9jd745i1kig9yw82hz335iys1lrp5",
    },
)

platform(
    name = "ash-coreutils-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-coreutils-x86_64-cc:kc209hp20raqvsv62prkdn9rfd1vh2fd",
    },
)

platform(
    name = "ash-i686",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-i686:2485g31rvlhs1wk5hipycickj6cr7b99",
    },
)

platform(
    name = "ash-i686-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-i686-cc:9inj16j7iwm5fn7h05lmr7l1zsvrg909",
    },
)

platform(
    name = "ash-i686-cc-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-i686-cc-x86_64:flkpdxrxhympjfr3662kmi4gh7ldg7f6",
    },
)

platform(
    name = "ash-i686-cc-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-i686-cc-x86_64-cc:z2dfrqcmry34lpnb42yjhnxgx9vqwxk0",
    },
)

platform(
    name = "ash-i686-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-i686-x86_64:6bckqrfvnz7hlygrj4djig1f6h2ag0hp",
    },
)

platform(
    name = "ash-i686-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-i686-x86_64-cc:02vl5frz6af314sfvrya2f5j8plgj35a",
    },
)

platform(
    name = "ash-strace",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-strace:2m035mwpyb00iq2lvdh878n58za0hx4i",
    },
)

platform(
    name = "ash-strace-coreutils",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-strace-coreutils:m5mngwxc1d497v0v6vix5cqgz91yrv4r",
    },
)

platform(
    name = "ash-strace-coreutils-i686",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-strace-coreutils-i686:6nvkw4l0ydz01yjv3cjbhwpn63a9nz10",
    },
)

platform(
    name = "ash-strace-coreutils-i686-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-strace-coreutils-i686-cc:lmc8b8zjg4sb65kij61h0zjnn20fpxzk",
    },
)

platform(
    name = "ash-strace-coreutils-i686-cc-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-strace-coreutils-i686-cc-x86_64:9k0rybv0zh21j1ii63nsgrv3igv5ah5g",
    },
)

platform(
    name = "ash-strace-coreutils-i686-cc-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-strace-coreutils-i686-cc-x86_64-cc:61s92xsa08y6q3cd015kbkphn8lpy4jv",
    },
)

platform(
    name = "ash-strace-coreutils-i686-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-strace-coreutils-i686-x86_64:v6zackmsprzyfz18qn5y4v9bia65wj7p",
    },
)

platform(
    name = "ash-strace-coreutils-i686-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-strace-coreutils-i686-x86_64-cc:ky15pdylaj8vzx4d0sq87nlf1sdc3gly",
    },
)

platform(
    name = "ash-strace-coreutils-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-strace-coreutils-x86_64:band3g0c4a2da2snqja7ibi55absa124",
    },
)

platform(
    name = "ash-strace-coreutils-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-strace-coreutils-x86_64-cc:lc67h832ykdqlfa2wi17hgh8bvc6n4pg",
    },
)

platform(
    name = "ash-strace-i686",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-strace-i686:l8nab0iym3h9j8zwrdjajclrj5bkchkw",
    },
)

platform(
    name = "ash-strace-i686-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-strace-i686-cc:6kqspd7pabz3sbzygc3h26a7mgr27vlr",
    },
)

platform(
    name = "ash-strace-i686-cc-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-strace-i686-cc-x86_64:i2s7jdakmxp06s2c5wgqy2vxnzajy5ms",
    },
)

platform(
    name = "ash-strace-i686-cc-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-strace-i686-cc-x86_64-cc:pnwxwiw6l5flfzqllzd0nbbq5hky81bj",
    },
)

platform(
    name = "ash-strace-i686-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-strace-i686-x86_64:y6hpj1iy1jnzbiqhb07kn666g9ycgklh",
    },
)

platform(
    name = "ash-strace-i686-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-strace-i686-x86_64-cc:fqr0sxq36g770z7ifd4rm0hw4jlcxb8b",
    },
)

platform(
    name = "ash-strace-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-strace-x86_64:96rywgz5g1nwpy22hb2d4hbn4vfhvjmr",
    },
)

platform(
    name = "ash-strace-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-strace-x86_64-cc:pmsn35y0crf9wm5iyd5lcmj4zw7mg02n",
    },
)

platform(
    name = "ash-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-x86_64:1js5dxr7rkm0rg50985mavw8i9flfz17",
    },
)

platform(
    name = "ash-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/ash-x86_64-cc:rgxmbwfqli1p3mnhm9sg11a1m7ijgkp9",
    },
)

platform(
    name = "bash",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/bash:zdv440mv2zipsi4iyzhxip8dygx13q2p",
    },
)

platform(
    name = "bash-coreutils",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/bash-coreutils:810xh7hnkcdm8pzy1ph4yz5zrwxgfaib",
    },
)

platform(
    name = "bash-coreutils-i686",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/bash-coreutils-i686:zb9dx707fh7j38qbzvqjdv4jbxcg1vr2",
    },
)

platform(
    name = "bash-coreutils-i686-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/bash-coreutils-i686-cc:7wxqw9p8584bl1z6hzrrnj7r8s0zs556",
    },
)

platform(
    name = "bash-coreutils-i686-cc-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/bash-coreutils-i686-cc-x86_64:hp1lrpjg38b7f46plykjyvcw8m2ib95a",
    },
)

platform(
    name = "bash-coreutils-i686-cc-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/bash-coreutils-i686-cc-x86_64-cc:qsq539d1kx6r3hfsqvml3ppchgy1ibg2",
    },
)

platform(
    name = "bash-coreutils-i686-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/bash-coreutils-i686-x86_64:scbxc97cpqzzhjss0rp5aala3hdy8i3d",
    },
)

platform(
    name = "bash-coreutils-i686-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/bash-coreutils-i686-x86_64-cc:d6wbqbb2g09zq0id9bvs0kgr5pj59sj7",
    },
)

platform(
    name = "bash-coreutils-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/bash-coreutils-x86_64:q8cwalhgv8p8jpmlvn504h30imzw8ahb",
    },
)

platform(
    name = "bash-coreutils-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/bash-coreutils-x86_64-cc:2wgjj260ff4aclgbgf8fi5wx7sbfxy9p",
    },
)

platform(
    name = "bash-i686",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/bash-i686:14c1jxf56db0bbfadhp569vnhw5jwg7v",
    },
)

platform(
    name = "bash-i686-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/bash-i686-cc:i1p04mml8r4is093i4m3ahxm6spiapqk",
    },
)

platform(
    name = "bash-i686-cc-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/bash-i686-cc-x86_64:ri1bsr9w2nim44zlv0fv4667w7pryrsa",
    },
)

platform(
    name = "bash-i686-cc-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/bash-i686-cc-x86_64-cc:1zxbag614b2z2nvmsr5y75hs5j3yg5zq",
    },
)

platform(
    name = "bash-i686-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/bash-i686-x86_64:5wqvldz6yqs2d9jx7lwayac9rzw5sz7a",
    },
)

platform(
    name = "bash-i686-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/bash-i686-x86_64-cc:383kzyxbmw3lbc8samsnsv6q2lr7wa98",
    },
)

platform(
    name = "bash-strace",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/bash-strace:c6n4ik5pp3vasfnhxnbzp8khjif5jh1v",
    },
)

platform(
    name = "bash-strace-coreutils",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/bash-strace-coreutils:z05cw1x87r0nwmh42av0pgpllvklfycl",
    },
)

platform(
    name = "bash-strace-coreutils-i686",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/bash-strace-coreutils-i686:l8z9bl2nvc6vvdxgpc51jyy1i968wm97",
    },
)

platform(
    name = "bash-strace-coreutils-i686-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/bash-strace-coreutils-i686-cc:xvw79ry7jvihdha31bh5qcfrkizkajs3",
    },
)

platform(
    name = "bash-strace-coreutils-i686-cc-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/bash-strace-coreutils-i686-cc-x86_64:hhpkas45l8nkm84xbwjxqc00iapklii5",
    },
)

platform(
    name = "bash-strace-coreutils-i686-cc-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/bash-strace-coreutils-i686-cc-x86_64-cc:d9jsnz7i4cja9rvc187yfv6r1l7gldig",
    },
)

platform(
    name = "bash-strace-coreutils-i686-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/bash-strace-coreutils-i686-x86_64:lfz44j773safzzlrhc995vg4cv30bi2a",
    },
)

platform(
    name = "bash-strace-coreutils-i686-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/bash-strace-coreutils-i686-x86_64-cc:m1fhf5im4v9wkw7wdrj9pyiclbsvs2jp",
    },
)

platform(
    name = "bash-strace-coreutils-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/bash-strace-coreutils-x86_64:5sc8a9gqd42r7k2v42nkv9mprwagq6hz",
    },
)

platform(
    name = "bash-strace-coreutils-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/bash-strace-coreutils-x86_64-cc:l697njg6hag3s131z300b9kk1r3xpffh",
    },
)

platform(
    name = "bash-strace-i686",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/bash-strace-i686:hl77f2lfwswxgr2qj323b6afzhvzszqn",
    },
)

platform(
    name = "bash-strace-i686-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/bash-strace-i686-cc:dczqxsfcshy8hjb01mhw6l7vbjb2rsld",
    },
)

platform(
    name = "bash-strace-i686-cc-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/bash-strace-i686-cc-x86_64:ji20flhn3lvh2r30qb50d6r43wib9sr6",
    },
)

platform(
    name = "bash-strace-i686-cc-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/bash-strace-i686-cc-x86_64-cc:13hp7hyvyc2d5kbdq1zpayi233gwmc7w",
    },
)

platform(
    name = "bash-strace-i686-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/bash-strace-i686-x86_64:qzf26ywskmlg1gq3aydifyllzjgap5ig",
    },
)

platform(
    name = "bash-strace-i686-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/bash-strace-i686-x86_64-cc:i18ppdfqd3kyi7gnm5wmfccyah5v69rn",
    },
)

platform(
    name = "bash-strace-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/bash-strace-x86_64:y3s8vb4rbvmzdby2jawgwjyc95p0z55q",
    },
)

platform(
    name = "bash-strace-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/bash-strace-x86_64-cc:m2dgwcl6hz8093bfv2ka8k653w7bg7a4",
    },
)

platform(
    name = "bash-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/bash-x86_64:m8j7gipnhyagzjq17xmny8jyxbqb90kk",
    },
)

platform(
    name = "bash-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/bash-x86_64-cc:vj250vi4yywzam7blz1xv3cs5zplj81r",
    },
)

platform(
    name = "coreutils",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/coreutils:glncz2bmqk2bv1midp2n8zpy7npshky8",
    },
)

platform(
    name = "coreutils-i686",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/coreutils-i686:pmhi8923gdcfgll4iq70zvl13sm50rda",
    },
)

platform(
    name = "coreutils-i686-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/coreutils-i686-cc:6dan6xm1vlqxyfb17jwqhxmx94kr4ind",
    },
)

platform(
    name = "coreutils-i686-cc-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/coreutils-i686-cc-x86_64:1mjw7fkaycrwwqw2yq57larnpj3183g3",
    },
)

platform(
    name = "coreutils-i686-cc-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/coreutils-i686-cc-x86_64-cc:9jz6arkpj6306v8aw83fp7cy47bzw1bh",
    },
)

platform(
    name = "coreutils-i686-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/coreutils-i686-x86_64:pcbhfachvs0zgp2m4asvyhjgfiqc0h2r",
    },
)

platform(
    name = "coreutils-i686-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/coreutils-i686-x86_64-cc:0a4kg9cqqv4zc3n1w9p5dl9x2fixlb15",
    },
)

platform(
    name = "coreutils-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/coreutils-x86_64:6zyvcbsypgfv796kpkynjgd0vfsrmb20",
    },
)

platform(
    name = "coreutils-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/coreutils-x86_64-cc:b1xnp82blrnmn73lfh0v9iw5q2rnnrhm",
    },
)

platform(
    name = "i686",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/i686:0imq1w2qwp0ac6zqs85dsf4rknj8q839",
    },
)

platform(
    name = "i686-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/i686-cc:rc0dyvp8aa5q3hnn1b72bilig1z6m5d9",
    },
)

platform(
    name = "i686-cc-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/i686-cc-x86_64:fghbm1gycyp2vz8pap9sj4cxcvp9pjc2",
    },
)

platform(
    name = "i686-cc-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/i686-cc-x86_64-cc:xjzg6sp6lfqvr6z0j06khlwcqxr5q5h5",
    },
)

platform(
    name = "i686-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/i686-x86_64:3jb53kjfc6yyxav5nmgnzbjpii8c6c84",
    },
)

platform(
    name = "i686-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/i686-x86_64-cc:3yccalha69sfk2lrx9wgkg5s7vv0b342",
    },
)

platform(
    name = "strace",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/strace:q8852n4a156mpydyk0z2qy6ydjqr006v",
    },
)

platform(
    name = "strace-coreutils",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/strace-coreutils:dmzy0c93k4wwljxwdm5kgwaqh2aqkv1w",
    },
)

platform(
    name = "strace-coreutils-i686",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/strace-coreutils-i686:qia11cxwhcz2c178f9pg9k8vkyv6z4v5",
    },
)

platform(
    name = "strace-coreutils-i686-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/strace-coreutils-i686-cc:nnsnkq5jdrnm2lmm7078x1jvc4f1vswj",
    },
)

platform(
    name = "strace-coreutils-i686-cc-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/strace-coreutils-i686-cc-x86_64:20i2bdgsg6pbfwiadb1p2s01h6lj3dip",
    },
)

platform(
    name = "strace-coreutils-i686-cc-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/strace-coreutils-i686-cc-x86_64-cc:3qcyr6hh0688d056sbh1ks56h375101n",
    },
)

platform(
    name = "strace-coreutils-i686-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/strace-coreutils-i686-x86_64:mqr3jlrn7bh08zak7660jxb5sk4z803x",
    },
)

platform(
    name = "strace-coreutils-i686-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/strace-coreutils-i686-x86_64-cc:qkm5zfj4mpfkp72n7970cy9ad9b1f7wl",
    },
)

platform(
    name = "strace-coreutils-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/strace-coreutils-x86_64:ww6yd49s4g8a4h9db99ypj4f4hk0g7sk",
    },
)

platform(
    name = "strace-coreutils-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/strace-coreutils-x86_64-cc:9h91ichn7hdcrrydnwsmgxpwadc3fbwp",
    },
)

platform(
    name = "strace-i686",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/strace-i686:w4z2f10jxp6mjy4l6ps3k304jpk44b0p",
    },
)

platform(
    name = "strace-i686-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/strace-i686-cc:vm15sa7x9apby123hj3iasxd6hv97ssb",
    },
)

platform(
    name = "strace-i686-cc-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/strace-i686-cc-x86_64:lsaz64yasihi2zlrh8770skdxifi0242",
    },
)

platform(
    name = "strace-i686-cc-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/strace-i686-cc-x86_64-cc:ypkpqqrdvdjd32as2alfa0s8jxsszqdz",
    },
)

platform(
    name = "strace-i686-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/strace-i686-x86_64:8yxxdg9arxkq4n7cbv5fiwfm3kpj3qyf",
    },
)

platform(
    name = "strace-i686-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/strace-i686-x86_64-cc:8il6cfzn3jp7zxbawnawc6cjflc49a0i",
    },
)

platform(
    name = "strace-x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/strace-x86_64:36gjjw1f5zygix764250inv5rma4a00h",
    },
)

platform(
    name = "strace-x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/strace-x86_64-cc:xs5czfckhqchcsmawn1cn92fb9mxw88q",
    },
)

platform(
    name = "x86_64",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/x86_64:xdf5axqb6al253wzlyxbis4xz2jjxf1y",
    },
)

platform(
    name = "x86_64-cc",
    parents = [":starterkit-x86_64-linux"],
    exec_properties = {
        "container-image": "docker://harbor.puqu.io/starterkit/x86_64-cc:93wbrsipsfkfmii2dadgp5gvvl3kldkp",
    },
)

