from_latest_tag = true
ignore_merge_commits = false
disable_changelog = false
disable_bump_commit = false
generate_mono_repository_global_tag = true

branch_whitelist = []

skip_ci = "[skip ci]"
skip_untracked = false

pre_bump_hooks = [
  # Lint
  "alejandra --check .",
  "statix check .",
  "cog check --from-latest-tag",
  # Build
  "nix-build default.nix -A images --no-out-link",
  # Test
  "nix-build default.nix -A images.test.all.run -o result-test-all.sh",
  "./result-test-all.sh",
  # Readme update
  "nix-build default.nix -A docs.readme -o result-readme",
  "cp -f result-readme ./README.md",
  # BUILD.bazel update
  "nix-build default.nix -A bzl.buildfile -o result-build-bazel",
  "cp -f result-build-bazel ./BUILD.bazel",
]
post_bump_hooks = []

pre_package_bump_hooks = []
post_package_bump_hooks = []
tag_prefix = "v"

[git_hooks]

[commit_types]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "starterkit"
owner = "explore-bzl"
authors = [
  { signature = "Aleksander Gondek", username = "AleksanderGondek" },
  { signature = "r2r", username = "r2r-dev" },
]

[bump_profiles]

[packages]
