name: "release"
run-name: "Release from commit ${{ github.sha }}"

on:
  push:
    branches: ["canon"]
    tags-ignore:
      # Never run for releases
      - 'v*'

jobs:
  release:
    name: "release"
    runs-on: ["ubuntu-latest"]
    defaults:
      run:
        shell: nix-shell --run "set -eo pipefail; source {0}"
 
    steps:
      - name: "Install nix"
        uses: cachix/install-nix-action@v26
        with:
          # This should not be here
          # as it introduces the possibility of someone
          # loading the wrong dependency by accident.
          # However, lack of this entry,
          # makes the GitHub action log output have
          # warnings regarding this, which makes
          # debugging harder if someone does not know
          # it can be ignored. 
          nix_path: nixpkgs=channel:nixos-unstable

      - name: "Checkout 'canon' branch of the repo"
        uses: actions/checkout@v4
        with:
          clean: true
          fetch-depth: 0
          fetch-tags: true
          # This is important, we do not do merges
          ref: ${{ github.event.pull_request.head.sha }}

      - name: "Set git users for release commit"
        run: |2
          git config user.name "Github Actions"
          git config user.email "actions@github.com"

      - name: "Auto-release"
        run: |2
          cog bump --auto --annotated 'automated release'

      - name: "Push changes"
        run: |2
          if [ $(git rev-list HEAD...origin/canon --ignore-submodules --count) -eq 0 ]; then
            echo "No commits to be pushed."
            exit 0
          fi

          # We are pushing the changes only if there are commits to be pushed
          git push
          git push --tags
